### ISSUE TITLE
Django 1.10 compatibility

### ISSUE THREAD

**Issue by metamatik** [django-parler/django-parler#150]
Hey there,

First of all, thank you for the work you are doing on this project :)

I am currently experimenting with the PostgreSQL full-text search feature implemented in Django 1.10. My first tests are encouraging, but we use `django-parler` in our real world projects, and right now I get an exception when trying to use it with Django 1.10b1.

The traceback is as follows:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/base.py", line 305, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/base.py", line 353, in execute
    self.check()
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/base.py", line 385, in check
    include_deployment_checks=include_deployment_checks,
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/management/base.py", line 372, in _run_checks
    return checks.run_checks(**kwargs)
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/Users/math/.virtualenvs/liitokala/lib/python3.5/site-packages/django/contrib/auth/checks.py", line 114, in check_models_permissions
    max_builtin_permission_name_length = max(len(name) for name in builtin_permissions.values())
ValueError: max() arg is an empty sequence
```

Hence: do you have plans to add Django 1.10 support? :)
If so, do you have even a vague idea of when we may expect it to be available? :)

Of course, I'm not asking you for any kind of commitment, it's just to get an idea about the next steps for our project.

Thanks in advance!

**Comment by vdboor** [comment]
Hi! Thanks for reporting this issue. It turns out this is a bug in Django 1.10, which will be fixed with the 1.10.1 release: https://docs.djangoproject.com/en/1.10/releases/1.10.1/

The `default_permissions = ()` was not properly handled in Django.

**Comment by metamatik** [comment]
Great! Thank you for the follow-up :)

**Comment by Artem19861910** [comment]
Hi there!
Today I've experienced lack of compatibility ( I have django 1.10.3 and when I try
`./manage.py makemigration myapp --name "add_translation_model"` shell showed me:
TypeError: The model 'Category' already has a field named 'name'

Later I saw, that django-parler is not compatible with my django.
