### ISSUE TITLE
AttributeError: 'IsMissing' object has no attribute 'slug' when caching enabled

### ISSUE THREAD

**Issue by jdgoettsch** [django-parler/django-parler#195]
Full traceback at the bottom. I'm not sure what I'm doing wrong.

This only happens with caching enabled. Setting `PARLER_ENABLE_CACHING = False` makes no difference. This occurs on a django-cms site inside an apphook.

When I send the output of this function to a template:

```python
from django.core.cache import cache
from django.utils.translation import get_language
from django.utils.translation import get_language_from_request
from parler.utils import get_active_language_choices
from project.models import Commodity

def current_commodities(req=None):
    if req:
        lang = get_language_from_request(req, check_path=True)
    else:
        lang = get_language()
    cache_key = 'current_commodities_{0}'.format(lang)

    commodities = cache.get(cache_key)
    if not commodities:
        organic = Commodity.objects.language('en').get(
            translations__language_code__in=get_active_language_choices(),
            translations__name='Organic')
        commodities = Commodity.objects.filter(
            translations__language_code__in=get_active_language_choices(),
            coststudy__archived=False
        ).distinct('translations__name').order_by('translations__name')
        commodities = set(commodities)
        commodities.add(organic)
        commodities = sorted(commodities, key=lambda c: c.name)
        cache.set(cache_key, commodities)

    return commodities
```

the translatable fields are inaccessible if a translation for the current language does not exist.

Here is my Commodity model:

```python
from django.core.urlresolvers import reverse
from django.conf import settings
from django.utils.translation import get_language
from parler.models import TranslatableModel
from parler.models import TranslatedFields

class Commodity(TranslatableModel):
    translations = TranslatedFields(
        name=models.CharField(
            max_length=32,
        ),
        slug=models.SlugField(
            editable=True,
            max_length=32,
        ),
        meta={
            'unique_together': [
                ('language_code', 'name'),
                ('language_code', 'slug'),
            ]
        },
    )

    search_siblings = models.ManyToManyField(
        'self',
        blank=True,
        help_text=u'Additional commodities to search for with this commodity.',
        symmetrical=False,
    )

    class Meta:
        app_label = u'are_cost_studies'
        verbose_name_plural = 'commodities'

    def __unicode__(self):
        return self.name

    def get_absolute_url(self, **kwargs):
        # django-cms menu creation conflicts (somehow) with parler caching
        try:
            slug = self.safe_translation_getter(
                'slug', language_code=get_language())
        except AttributeError:
            slug = self.safe_translation_getter(
                'slug', language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)

        if 'archived' in kwargs.keys():
            return reverse(
                'are_cost_studies_archived_commodity',
                kwargs={'slug': slug})
        else:
            return reverse(
                'are_cost_studies_commodity', kwargs={'slug': slug})
```

You can see I had this issue in the `get_absolute_url` method above but was able to work around it; I'm not sure I can work around the issue in the templates.

and my template code where it fails:

```

{% for commodity in commodities %}
  <option value="{{ commodity.slug }}">{{ commodity.name }}</option>
{% endfor %}
```

Settings:
```python
USE_I18N = True

LOCALE_PATHS = (
    'project/locale',
)

LANGUAGES = (
    ('en', _('English')),
    ('es', _('Spanish')),
)
CMS_LANGUAGES[4] = [
    {
        'code': 'en',
        'name': _('English'),
        'public': True,
        'redirect_on_fallback': False,
    }, {
        'code': 'es',
        'name': _('Spanish'),
        'public': True,
        'fallbacks': ['en'],
        'redirect_on_fallback': False,
    },
]

PARLER_DEFAULT_LANGUAGE_CODE = 'en'

PARLER_LANGUAGES = {
    SITE_ID: (
        {'code': 'en'},
        {'code': 'es'},
    ),
    'default': {
        'fallbacks': ['en'],
        'hide_untranslated': False,
    }
}

PARLER_ENABLE_CACHING = False
```

Full traceback:
```python
ERROR Internal Server Error: /es/current/region/central-coast/
Traceback (most recent call last):
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/core/handlers/base.py", line 164, in get_response
    response = response.render()
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/response.py", line 158, in render
    self.content = self.rendered_content
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/response.py", line 135, in rendered_content
    content = template.render(context, self._request)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/backends/django.py", line 74, in render
    return self.template.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 210, in render
    return self._render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 93, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 93, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/sekizai/templatetags/sekizai_tags.py", line 93, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/classytags/core.py", line 153, in render
    return self.render_tag(context, **kwargs)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/cms/templatetags/cms_tags.py", line 498, in render_tag
    rendered_contents = nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 444, in render
    return strip_spaces_between_tags(self.nodelist.render(context).strip())
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 329, in render
    return nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 576, in render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/loader_tags.py", line 159, in render
    return template.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 212, in render
    return self._render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/test/utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 905, in render
    bit = self.render_node(node, context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 79, in render_node
    return node.render(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/defaulttags.py", line 217, in render
    nodelist.append(node.render(context))
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/debug.py", line 89, in render
    output = self.filter_expression.resolve(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 648, in resolve
    obj = self.var.resolve(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 789, in resolve
    value = self._resolve_lookup(context)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/django/template/base.py", line 827, in _resolve_lookup
    current = getattr(current, bit)
  File "/home/jeff/.virtualenvs/project/lib/python2.7/site-packages/parler/fields.py", line 102, in __get__
    return getattr(translation, self.field.name)
AttributeError: 'IsMissing' object has no attribute 'slug'
```

**Comment by vdboor** [comment]
Yikes! It looks like our `IsMissing` flag leaked outside the internal object cache. We use that flag to denote that a certain translation or fallback is known not to exist, so it won't be requested again.

I found one case where this might happen. Can you test with the latest git version, to see if this fixes your bug?

**Comment by jdgoettsch** [comment]
Unfortunately this does not fix the issue.

**Comment by jdgoettsch** [comment]
This line: 
https://github.com/django-parler/django-parler/blob/7f8562836d021e657558b844e01f88f7a1b67f8a/parler/models.py#L478

Should be:

```python
if not object:
```

That fixes the issue.

**Comment by vdboor** [comment]
Thanks @jdgoettsch!
