### ISSUE TITLE
Added translated field, now non-numeric primary key is causing problem

### ISSUE THREAD

**Issue by rasmus-storjohann-PG** [django-parler/django-parler#201]
This is the change I made
```
 from django.db import models
+from parler.models import TranslatableModel, TranslatedFields
 
-class Organization(models.Model):
-    id = models.CharField(primary_key=True, blank=False, max_length=200)
+class Organization(TranslatableModel):
+    id = models.CharField(primary_key=True, blank=False, max_length=200),
+    translations = TranslatedFields(
+        name=models.TextField(blank=False)
+    )
 
     def __str__(self):
         return self.id
```
Now when I run my unit tests, which passed before, I get an error because it wants to translate the primary key "The id" to a number. Is there an assumption in django-parler that primary keys are numeric?
```
Traceback (most recent call last):
  File "/home/rasmus/git/pathways-backend/organizations/tests/test_models.py", line 11, in test_has_id
    organization.save()
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/parler/models.py", line 657, in save
    super(TranslatableModelMixin, self).save(*args, **kwargs)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/base.py", line 808, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/base.py", line 838, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/base.py", line 905, in _save_table
    forced_update)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/base.py", line 935, in _do_update
    filtered = base_qs.filter(pk=pk_val)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/query.py", line 784, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/query.py", line 802, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1250, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1276, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1210, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1104, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/rasmus/git/PW/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'The id'
```

**Comment by rasmus-storjohann-PG** [comment]
Problem unrelated to django-parler, please ignore
